--- 

version: '3'

services:
  db:
    image: postgres:14.7-alpine
    restart: always
    environment:
      POSTGRES_DB: essentialdb
      POSTGRES_USER: essential_photo_backend
      POSTGRES_PASSWORD: postgres
    command: "postgres -c 'max_connections=500'"
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  backend: 
    build: https://github.com/esteban90-dev/essential-photo-backend.git#main
    command: rails s -p 3001
    ports:
      - '3001:3001'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: essentialdb
      DB_USER: essential_photo_backend
      DB_PASSWORD: postgres
      ESSENTIAL_PHOTO_BACKEND_DATABASE_PASSWORD: postgres
  frontend:
    build: https://github.com/esteban90-dev/essential-photo-frontend.git#main
    command: npm start
    ports:
      - '3000:3000'
    depends_on:
      - backend
volumes:
  db:
    driver: local
networks:
  default:
    name: default_network
